// =============================================================================
// File:        ntt_twiddle_rom.sv
// Project:     Dilithium Post-Quantum Signature Hardware Implementation
// Module:      ntt_twiddle_rom
// Description: Read-only memory holding the 256 pre-computed NTT twiddle
//              factors (zetas) used by the Dilithium reference C code.
//
//              The ROM is 256 entries deep, 24 bits wide. Values are loaded
//              from the ntt_params package, which in turn is generated by
//              scripts/gen_twiddles.py from ref/ntt.c.
//
// Author:      Generated for Dilithium HW IP Core
// Date:        2026-06-23
// Version:     1.0 (Phase 1: Core Arithmetic Units)
//
// Compliance:  IEEE 1800-2017 SystemVerilog, synthesizable.
// =============================================================================

`ifndef DILITHIUM_NTT_TWIDDLE_ROM_SV
`define DILITHIUM_NTT_TWIDDLE_ROM_SV

`include "dilithium_pkg.sv"
`include "ntt_params.svh"

module ntt_twiddle_rom #(
    parameter int unsigned ADDR_WIDTH = 8,    // 256 entries
    parameter int unsigned DATA_WIDTH = 24
) (
    input  logic                    clk,
    input  logic                    re,       // read enable
    input  logic [ADDR_WIDTH-1:0]   addr,
    output logic signed [DATA_WIDTH-1:0] rdata
);

  // Memory array
  logic signed [DATA_WIDTH-1:0] mem [0:255];

  // Initialise from the ntt_params package (synthesis: becomes ROM init;
  // simulation: filled at time 0).
  initial begin
    for (int i = 0; i < 256; i++) begin
      mem[i] = ntt_params::ZETAS[i];
    end
  end

  // Single-port synchronous read
  always_ff @(posedge clk) begin
    if (re) rdata <= mem[addr];
  end

endmodule

`endif // DILITHIUM_NTT_TWIDDLE_ROM_SV
